### ISSUE TITLE
Pixelation shader doesn't compile on Android in Flutter 3.22.2

### ISSUE THREAD

**Issue by Spooky12** [jonahwilliams/flutter_shaders#35]
When I include `packages/flutter_shaders/shaders/pixelation.frag` in `pubspec.yaml` Android doesn't compile anymore in Flutter 3.22.2

<details>
  <summary>Error thrown</summary>
  
```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
lib/main.dart:1
Compilation failed.
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag: GLSL to SPIRV failed; Compilation error. 0 error(s) and 2 warning(s).
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag:10: warning: 'uPixels' : ignoring layout qualifier for uniform location
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag:11: warning: 'uSize' : ignoring layout qualifier for uniform location
shaderc: internal error: compilation succeeded but failed to optimize: [VUID-StandaloneSpirv-Location-06672] Location decoration must not be applied to this storage class
  %uTexture = OpVariable %_ptr_UniformConstant_44 UniformConstant





Target debug_android_application failed: ShaderCompilerException: Shader compilation of "/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag" to "/Users/thomas/Projects/test_shader/build/app/intermediates/flutter/debug/flutter_assets/packages/flutter_shaders/shaders/pixelation.frag" failed with exit code 1.
impellerc stdout:

impellerc stderr:
Compilation failed.
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag: GLSL to SPIRV failed; Compilation error. 0 error(s) and 2 warning(s).
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag:10: warning: 'uPixels' : ignoring layout qualifier for uniform location
/Users/thomas/.pub-cache/hosted/pub.dev/flutter_shaders-0.1.2/lib/shaders/pixelation.frag:11: warning: 'uSize' : ignoring layout qualifier for uniform location
shaderc: internal error: compilation succeeded but failed to optimize: [VUID-StandaloneSpirv-Location-06672] Location decoration must not be applied to this storage class
  %uTexture = OpVariable %_ptr_UniformConstant_44 UniformConstant
9

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/thomas/fvm/versions/stable/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Error: Gradle task assembleDebug failed with exit code 1
Exited (1)
```
</details>

<details>
  <summary>My pubspec.yaml</summary>
  
```yaml
name: test_shader
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_shaders: ^0.1.2
  svg_path_parser: ^1.1.2
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  shaders:
    - packages/flutter_shaders/shaders/pixelation.frag
    - assets/shaders/foil.frag
    - assets/shaders/fractal.frag
    - assets/shaders/circles.frag
    - assets/shaders/test.frag

```
</details>

It works fine on other platforms (ios/web/macos) in Flutter 3.22.2 and on Android in Flutter 3.19.4

I don't have the issue with my other shaders
